import Head from "next/head";
import Navbar from "../components/navbar";
import styles from "../styles/Layout.module.css"
import Footer from "./footer";

interface LayoutProps {
  children: React.ReactNode;
};
export default function Layout({ children }: LayoutProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar items={[{
        href: "/", text: "HOME"
      },
      {
        href: "/about", text: "ABOUT"
      }
      ]} />
        
      <main>
        {children}
      </main>

      <Footer />
    </div>
  );
}